# Notes About this Notebook
This notebook was developed to support the education of Master's Students in the Governance of Sustainability Program at Leiden University in learning to create figures with the help of python. This notebook is one of two notebooks designed for this educational course and should be read as the first (1 of 2) in the exercise. 

If you use these notebooks or the accompanying excel workbook to develop your own activities or teaching modules please cite this workshop: 

Logan, H.M. (2026), Data Vizualization Workshop - Thematic Course 1. Governance of Sustainability, Masters Program, 2026-2027. Leiden University, Leiden, NL.

# Intro to Python (for new coders)

If this peaks your interest and you decide you want to learn python or more about data science, check out these resources:
* Online class you can audit for free: https://pll.harvard.edu/course/cs50s-introduction-programming-python
* Online courses (Paid but basics on python and data analysis are free): https://pychallenger.com/python-basics/
* Great books: Python Crash Course https://nostarch.com/python-crash-course-3rd-edition
* Dive into data science (for those of you totally new to working with data for analysis) https://nostarch.com/dive-data-science
* Practice: https://pynative.com/python-exercises-with-solutions/

# Data Viz Workshop Part 1

### Getting Started: 

We are working in a Jupyter notebook. For those of you who aren't super comfortable with coding Jupyter notebooks are just a way of communicating markdown (text like this) and python code in small sections. This lets you be able to follow what going on or practice making changes to code without having to work with a giant code file. As you go from section to section you can execute the code step by step by selecting the "run" button for each block or clicking the block typing ctrl+enter at the same time.  


If you start using IE tools such as MFA, EEIO, or LCA you may be using a lot of jupyter notebooks, so it's good to get familiar with how they run. You can either run this in Visual Studio Code (VSCode), Jupyter Lab, Google Co-lab or in another code manager of your choice. If you are having problems, work with a group member to go through the code and then we can have a separate meeting to go over your computer set up to find the errors. .
# Getting started with Data Vizaulization

In today's exercise we are going to learn how we can communicate data and information using python.

In this notebook you will learn how to create and/or import data into a dataframe in python and develop simple figures. 

Once you feel comfortable here move on to notebook two where you will learn more visualization options and start to develop your own dashboard. **It will be up to you to choose the figures which suit your story best, pull the correct data, and interpret your findings as you believe your stakeholder would**.

# Packages we need

* Pandas - Process and transform data
* Numpys - Work with numbers in pythong (num and py ;) )
* Plotly - Make figures and graphs

In [ ]:
# So we start by installing the packages we need using pip
# pip is a package manager we often use in python
# to use pip to install a python package we want we type: !pip install [package_name]

!pip install plotly
#plotly is a common packaging for making plots and graphs
!pip install numpy
#Numpy allows us to do math in python 
!pip install pandas
# Pandas is a package for data analysis in python we will need it to bring excel data in and out of the graphs

# Once you execute you will get an output below this box
# if you are using colab you will  hopefully see that all the requirements are already satisfied
# this code block is mostly for if you bring this notbook with you to use in your IGA 2 or future courses

#### Read the Docs

Whenever you start using a new python package its important you "read the docs" to understand how the code is intended to work and the different features of a package. It's also a good place to go to figure out common "bugs" or even find inspiratation for your coding.  You don't have to do this to work with this notebook, but if you want to become a better coder learning to read and reference the docs is a good skill to develop. 

**Plotly docs**: https://plotly.com/python/

**Pandas docs**: https://pandas.pydata.org/docs/ 

**Numpy docs**: https://numpy.org/doc/

In [ ]:
# Once we install a package we can import it when we want to use its functions.
# There are often common abbreviations so we don't have to write out the package name every single time.
# These are standardized so plotly.express is always px and pandas is always pd etc. 
# You can change the abbreviation, but if you share your code, try to use the most common abbreviation. 

import plotly.express as px
import pandas as pd
import numpy as np

# Making a Data Table in (DataFrame) in python (from scratch)

When we create a graph in python we need to start by creating a object. In this case the object we are creating is a data frame (df). In python a df is what we would call a table in excel.

## Creating an object

To create an object we need to name it and then assign data or information to it.

so in the code block below we would write

object = [CODE HERE]

Here we use "object =" to tell the computer that this object that I have named object contains the following data/information.

We can change the name of the object to something we remember

EU_data = [CODE HERE]

Here we use "object =" to tell the computer that this object that I have named EU_data contains the following data/information.

## Assigning data to an object

Then we want to assign information to the object.

I am going to skip a whole introduction to lists, tuples, and dictionaries here. You should go learn about these from one of the sources I link above. For right now we just want to figure out how to assign a table of data to our object.

Let's say we have this table we want to use as a dataframe (df) for our graph.

 | Country | MF(2023)|
 |---------|--------------------------|
 |Netherlands| 1.0|
 |Denmark| 2.0|
 |Spain| 1.5|

To assign this to our object we would write the following:

    object = pd.DataFrame({
      "Column A Name" : ["Row 1", "Row 2", "Row 3"],
      "Column B Name" : ["Row 1", "Row 2", "Row 3"],})

And with our actual data we would write:

    EU_data = pd.DataFrame({
        "Country" : ["Netherlands", "Denmark", "Spain"],
        "MF(2023)" : ["1.0", "2.0", "1.5",],})

Okay so now we want to see that our data matches what we expected to see so we print (display) the object we have created in the output below the coding block.


Run the coding block below now to try this on your own.

In [216]:
# Creating an object.
EU_data = ("data")
#Now we have made an object we called EU_data and assigned it "data"
EU_data
# If we print/display the object you can see what it contians below

'data'

In [217]:
# Adding our table/dataframe to our object

EU_data = pd.DataFrame({
      "Column A Name" : ["Row 1", "Row 2", "Row 3"],
      "Column B Name" : ["Row 1", "Row 2", "Row 3"],})
# Now we print to see if we changed what data is there

EU_data

  Column A Name Column B Name
0         Row 1         Row 1
1         Row 2         Row 2
2         Row 3         Row 3

In [218]:
# Updating our table to have real data
# So now we replace with the data from our table
EU_data = pd.DataFrame({
        "Country" : ["Netherlands", "Denmark", "Spain"],
        "MF(2023)" : ["1.0", "2.0", "1.5",],})
# Now we print to see if we changed what data is there

EU_data

       Country MF(2023)
0  Netherlands      1.0
1      Denmark      2.0
2        Spain      1.5

In [ ]:

# Notice that whenever we change something behind the equal sign in "EU_data ="
# the data that prints/output changes
# this means if you want to have both the example table and the real data you would need two objects/dataframes

# let try it
example = pd.DataFrame({
      "Column A Name" : ["Row 1", "Row 2", "Row 3"],
      "Column B Name" : ["Row 1", "Row 2", "Row 3"],})
example

  Column A Name Column B Name
0         Row 1         Row 1
1         Row 2         Row 2
2         Row 3         Row 3

In [220]:
EU_data
# So now you can see that we have two objects
# one called example with out table set up
# one called EU_data with our real data

# This is important to keep in mind
# if you just change the data behind the "=" for an object,
# then you will reassign the data and replace the previous data

       Country MF(2023)
0  Netherlands      1.0
1      Denmark      2.0
2        Spain      1.5

# Making Graphs

Now that you now ho to assign a dataframe (table) to an object. Now Let's see how we can use that to make figures.

We are going to use PLOTLY for figures just like introduced in the notebook yesterday.

When you choose the figure you want to make you need to think about which kind of relationship you are going to demonstrate and what can be present on the access. In our table we have two types of data locations and a single set of values:

 | Country | MF(2023)|
 |---------|--------------------------|
 |Netherlands| 1.0|
 |Denmark| 2.0|
 |Spain| 1.5|


 So this means we can make, for example, bar charts showing the MF per country in 2023.

 # Creating a figure

So first we need to import the package. The name of the package is “plotly.express” and it as almost always named “px” in code. This is just a python/plotly rule. I don’t know why, but just like learning any language there are some rules we choose to accept.

    import plotly.express as px

This means we have imported the files we need to create graphs and we call the package plotly.express “px” in our code from here on out, (which will save us the headache of typing plotly.express out every time). We did this at the top of the notebook so you don't need to call it again (but it won't hurt anything if you do).

To create a figure we first assign an object, in this case we will call it fig_bar:

    fig_bar =[CODE HERE]

Next, we will need to add code to call the figure, this is where “px” comes in.

    [Object Name]=px.[Type of Graph]([DataFrame], x = [“Column A Name”], y = [“Column B Name”])

So for [Type of Graph], we want a “bar”, for [DataFrame] we want to call "EU_data", for [“Column A Name”] we call "Country”, and for we call MF(2023). This will result in the following code.

    fig_bar=px.bar(EU_data, x = “County”, y = “MF(2023)")

Then to show the graph we will type the name of the object and “.show()”.

    fig_bar.show()

In [221]:
# bar chart (Requires 2 columns of data)
fig_bar=px.bar(EU_data, x = "Country", y = "MF(2023)",)

fig_bar.show()

In [222]:
fig_bar=px.bar(EU_data, x = "Country", y = "MF(2023)", #data

              # The first line is the ony required line everything below is a nice to have addition

                title = "Material Footprint by EU Country in 2023",
               # Title of the figure

                hover_data = ["Country","MF(2023)"],
               # What you see when you hover your mouse on a bar in the figure

                color = "MF(2023)",
               # Assigns colors by country name try changing this to "MF(2023)" to see a difference

                color_discrete_sequence = px.colors.qualitative.Pastel,
               # Color scheme (try px.colors.qualitative.Plotly)

                template ="plotly",
               # Sets the general template for the figure (try "plotly_white" or "plotly_dark")

                labels = {"MF(2023)":'Material Footprint 2023'},
               # What the value in the assigned axis and hover_data is called

                height = 400,
               # 400 is a small figure 1000 is a tall figure

                width = 400,
               # width of the figure
 )


fig_bar.show()

# Congrats!

You have made your first bar graph with Python and Plotly.

Now you may say:

>"Heath, that's cool but I don't want to type out 50 lines of data like this!"

or maybe

>"Heath, I have like 10 columns, I want to make a figure quickly!"

#Dealing with time in Data Visualization.

In working with the EU monitoring data you will usually work with time over years.  I.e. waste generation in Denmark for 202, 2021,2022, and so on.

## So how might you make a graph that deals with time?

Let's start with the following table:

|Country| 2020|2021|2022|
|--|--|--|--|
|DK| 1|2|3|
|NL|2|3|1|
|ESP|3|1|2|


Then we assign the DataFrame as an object with a name:
    
    MF_yrs_data = pd.DataFrame({
    "Country": ["DK", "NL", "ESP"],
    "2020": [1, 2, 3],
    "2021": [2, 3, 1],
    "2022": [3, 1, 2],})


As befre we show the dataframe:

    MF_yrs_data

In [223]:
#setting up a dataframe with time
MF_yrs_data = pd.DataFrame({
  "Country": ["DK", "NL", "ESP"],
  "2020": [1, 2, 3],
  "2021": [2, 3, 1],
  "2022": [3, 1, 2],})

MF_yrs_data

  Country  2020  2021  2022
0      DK     1     2     3
1      NL     2     3     1
2     ESP     3     1     2

#Graphing with time
So the bar graph will work if you want to call a single year or compare the years along side each other.

## Single Year Call Outs
To show a single year we just call the bar chart as before but update the y column for the year we want to call.

    fig_bar_2020=px.bar(MF_yrs_data, x = "Country", y = "2020",)

and show the new graph

    fig_bar_2020.show()

#Multiple Years
To show multiple years, we add all the years we want to call to the y axis

    fig_bar_yrs=px.bar(MF_yrs_data, x = "Country", y = ["2020","2021","2022"],)

And we need to update our figure layout to change the default display of the graph, which can be any of the following [“OPTION”]: 'stack', 'group', 'overlay', 'relative'.

    fig_bar_yrs.update_layout(barmode =[“OPTION”])

And in this case we choose to group

    fig_bar_yrs.update_layout(barmode = "group")

And because we have multiple data points on the y axis we update the label:

    fig_bar_yrs.layout.yaxis.title = "Material Footprint per year (t/pp)"

So the full code would look like:

    fig_bar_yrs=px.bar(MF_yrs_data,
    x = "Country",
    y = ["2020","2021","2022"],)

    fig_bar_yrs.update_layout(barmode = "group" )

    fig_bar_yrs.show()

In [224]:
#show a single year
fig_bar_yrs=px.bar(MF_yrs_data, x = "Country", y = "2020",
                   labels = {"2020":"Material Footprint 2020"})

fig_bar_yrs.show()

In [225]:
#show a multiple years
fig_bar_yrs=px.bar(MF_yrs_data,
                   x = "Country",
                   y = ["2020","2021","2022"],
                   )
fig_bar_yrs.update_layout(barmode = "group")

fig_bar_yrs.layout.yaxis.title = "Material Footprint per year (t/pp)"

fig_bar_yrs.show()

# Making Scatter and Line Plots: Transform the Data

So because our data looks like this:
|Country| 2020|2021|2022|
|--|--|--|--|
|DK| 1|2|3|
|NL|2|3|1|
|ESP|3|1|2|

We need to either invert our data or create a melt to plot our values against our years.

### Inverting data by Index

Inverting our data is just like when you copy something in excel and use the "paste special" function to switch the columns and rows. We use the ".setindex().T" function to do this.

So first we call our dataframe and then ".setindex("COLUMN NAME").T"

    df_i = df.setindex("COLUMN NAME").T

In our case:

    MF_yrs_data_i = MF_yrs_data.set_index("Country").T

This will then make our data look like:

| Country | DK | NL | ESP |
|------|---:|---:|----:|
| 2020 |  1 |  2 |   3 |
| 2021 |  2 |  3 |   1 |
| 2022 |  3 |  1 |   2 |

Now we want to re-name column "Country" to blank, reindex the table, and rename the new column with years:

    MF_yrs_data_i = MF_yrs_data.set_index("Country").T
    # turns the dataframe
    MF_yrs_data_i.columns.name = ""
    # resets the name of the first column to blank
    MF_yrs_data_i = MF_yrs_data_i.reset_index()
    # re indexes the df
    MF_yrs_data_i.rename(columns={"index": "Year"}, inplace=True)
    #names the first column "years"
    

And now if you print/display:  
    
    MF_yrs_data_i

You will see:

| Years | DK | NL | ESP |
|------|---:|---:|----:|
| 2020 |  1 |  2 |   3 |
| 2021 |  2 |  3 |   1 |
| 2022 |  3 |  1 |   2 |

### Inverting Data in Excel

You can always make a new sheet, save, re-upload, and create a new dataframe

### Inverting data via a melt

A melt create a different dataframe structure. Essentially it will combine all four columns into two columns, esentially elongating the dataframe. This is sometimes called long or melt depending on the code you are looking at.

To do this:

    MF_yrs_data_melt = MF_yrs_data.melt(
    id_vars="Country", # sets the indexing column
    # i.e. we will make 3 extra rows for each country
    var_name="Year", # This determines the name to the new column
    value_name="MF" # This asigns the value to the the new row)

And then when we print/display the dataframe

    MF_yrs_data_melt

It will look like this:

| Country | Year | MF |
|---------|------|---:|
| DK      | 2020 |  1 |
| NL      | 2020 |  2 |
| ESP     | 2020 |  3 |
| DK      | 2021 |  2 |
| NL      | 2021 |  3 |
| ESP     | 2021 |  1 |
| DK      | 2022 |  3 |
| NL      | 2022 |  1 |
| ESP     | 2022 |  2 |

In [226]:
# Inverting the Dataframe
MF_yrs_data_i = MF_yrs_data.set_index("Country").T
# turns the dataframe
MF_yrs_data_i.columns.name = ""
# resets the name of the first column to blank
MF_yrs_data_i = MF_yrs_data_i.reset_index()
# re indexes the df
MF_yrs_data_i.rename(columns={"index": "Year"}, inplace=True)
# names the first column "years"


MF_yrs_data_i

   Year  DK  NL  ESP
0  2020   1   2    3
1  2021   2   3    1
2  2022   3   1    2

In [227]:
# Elongating/Melting the data frame

MF_yrs_data_melt = MF_yrs_data.melt(
    id_vars="Country", # sets the indexing column
    # i.e. we will make 3 extra rows for each country
    var_name="Year", # This determines the name to the new column
    value_name="MF", # This asigns the value to the the new row
    )

MF_yrs_data_melt

  Country  Year  MF
0      DK  2020   1
1      NL  2020   2
2     ESP  2020   3
3      DK  2021   2
4      NL  2021   3
5     ESP  2021   1
6      DK  2022   3
7      NL  2022   1
8     ESP  2022   2

In [228]:
# Line Chart with Inverted Data

fig_line_i= px.line(MF_yrs_data_i, x="Year", y=["DK","NL", "ESP"],
               )
fig_line_i.layout.yaxis.title = "Material Footprint (t/pp)"
fig_line_i.layout.legend.title = "Country"
fig_line_i.show()

In [229]:
# Line Chart with Melted Data

fig_line_melt= px.line(MF_yrs_data_melt, x="Year", y=["MF"],
                  color = "Country",
               )
fig_line_melt.layout.yaxis.title = "Material Footprint (t/pp)"
fig_line_melt.show()

## Scatter Plots

### With inverted data
So as before we create and name an object, we call plotly.express as px, and we choose our figure type (line). Then we assign our new inverted data names

    fig_scatter_i = px.scatter(MF_yrs_data_i,
                      x="Year",
                      y=["DK","NL", "ESP"]
                      )

And now we show the graph

    fig_scatter_i.show()

### With melted data
So as before we create and name an object, we call plotly.express as px, and we choose our figure type (line). Then we assign our new melted column names

    fig_scatter_melt= px.line(MF_yrs_data_melt, x="Year", y=["MF"],
                  color = "Country",
               )
and then we show:

    fig_scatter_melt.show()

In [230]:
fig_scatter_i = px.scatter(MF_yrs_data_i,
                  x="Year",
                  y=["DK","NL", "ESP"]
                  )
fig_scatter_i.layout.yaxis.title = "Material Footprint (t/pp)"
fig_scatter_i.layout.legend.title = "Country"
fig_scatter_i.show()

In [231]:
fig_scatter_melt= px.scatter(MF_yrs_data_melt, x="Year", y=["MF"],
              color = "Country",
           )
fig_scatter_melt.show()


# How to import data from excel

So just like when we made our DataFrame (table), we are going to use pandas to import our full data list.
To do this we

* Name an object
*	Assign a data frame

This looks like:
    
    Object = pd.read_excel( [“Path”] , Sheet name=[“Sheet”])

So, for us object is “EU_new_data”, [“Path”]  is  "/content/dataviz_ws.xlsx", and the [“Sheet”]is “dataviz_simple” this will look like:

    EU_new_data = pd.read_excel("/content/dataviz_ws.xlsx", sheet_name = "dataviz_simple")

Now in the data viz workbook I have added a worksheet named “dataviz_simple” with a small set of data that looks like this:
| Country         | ISO | MF (t/pp) |
|----------------|-----|-----------:|
| Austria        | AUT | 25.358324 |
| Belgium        | BEL | 45.566686 |
| Denmark        | DNK | 26.229685 |
| France         | FRA | 17.267028 |
| Germany        | DEU | 23.970287 |
| Slovakia       | SVK | 17.117922 |
| Sweden         | SWE | 24.119369 |
| Switzerland    | CHE | 39.497184 |
| Ukraine        | UKR | 9.729827 |
| United Kingdom | GBR | 17.077014 |

In [232]:
# import data from excel
EU_new_data = pd.read_excel("/content/dataviz_ws.xlsx", sheet_name = "dataviz_simple")
EU_new_data

          Country  ISO  MF (t/pp)
0         Austria  AUT  25.358324
1         Belgium  BEL  45.566686
2         Denmark  DNK  26.229685
3          France  FRA  17.267028
4         Germany  DEU  23.970287
5        Slovakia  SVK  17.117922
6          Sweden  SWE  24.119369
7     Switzerland  CHE  39.497184
8         Ukraine  UKR   9.729827
9  United Kingdom  GBR  17.077014

In [233]:
# Make a bar chart
fig_bar_2=px.bar(EU_new_data, x = "Country", y = "MF (t/pp)", #data

              # The first line is the ony required line everything below is a nice to have addition

                title = "Material Footprint (tonnes/per person) by Country in 2023",
               # Title of the figure

                hover_data = ["Country","MF (t/pp)"],
               # What you see when you hover your mouse on a bar in the figure

                color = "MF (t/pp)",
               # Assigns colors by country name try changing this to "MF(2023)" to see a difference

                color_continuous_scale=[
                         [0, "yellow"],
                          [0.5, "red"],
                           [1, "purple"]],
               # Color scheme (instead of using the existing I want to assign my own)
               # Notice I changed the object to color_continuous_scale to allow this
               # Previously it was color_discrete_sequence

                template ="plotly",
               # Sets the general template for the figure (try "plotly_white" or "plotly_dark")

                labels = {"MF (t/pp)":'MF (t/pp)'},
               # What the value in the assigned axis and hover_data is called

                height = 400,
               # 400 is a small figure 1000 is a tall figure

                width = 600,
               # width of the figure
 )


fig_bar_2.show()

# What if I want to make a stacked bar chart?

Great question. So here we need to do a little data cleaning to make this possible. This can be done in 1 of 2 ways either in python or in excel. If you are doing this in Excel, remember the Data Cleaning Rules to Keep in Mind (end of this section).

So in python we can do this by adding a new row to our dataframe(df):

    df["NEW COLUMN NAME"] = "Value"

In our case this would look like:

    EU_new_data["Region"] = "World"

If we print/display this code we now see we have a new column.

    EU_new_data

That looks like this:
| Country         | ISO | MF (t/pp) | Region |
|----------------|-----|----------:|--------|
| Austria        | AUT | 25.358324 | World  |
| Belgium        | BEL | 45.566686 | World  |
| Denmark        | DNK | 26.229685 | World  |
| France         | FRA | 17.267028 | World  |
| Germany        | DEU | 23.970287 | World  |
| Slovakia       | SVK | 17.117922 | World  |
| Sweden         | SWE | 24.119369 | World  |
| Switzerland    | CHE | 39.497184 | World  |
| Ukraine        | UKR | 9.729827  | World  |
| United Kingdom | GBR | 17.077014 | World  |

In [234]:
# Try to add the new column
EU_new_data['Region'] = "World"

EU_new_data

          Country  ISO  MF (t/pp) Region
0         Austria  AUT  25.358324  World
1         Belgium  BEL  45.566686  World
2         Denmark  DNK  26.229685  World
3          France  FRA  17.267028  World
4         Germany  DEU  23.970287  World
5        Slovakia  SVK  17.117922  World
6          Sweden  SWE  24.119369  World
7     Switzerland  CHE  39.497184  World
8         Ukraine  UKR   9.729827  World
9  United Kingdom  GBR  17.077014  World

# Get to the Stacking Already!
Okay so as before:
1.	we name the object
2.	call plotly.express and the type of graph (bar)
3.	we call our dataframe(table)
4.	assign the x and y axis to the columns we wish to call
5.	assign the color to the bars by country
6.	add a title

    fig_bar_3 = px.bar(EU_new_data, x="Region", y= "MF (t/pp)",
                   color = "Country",
                   title = "Cumulative Material Footprint (tonnes/per person) by Region in 2023",)

Then we show our figure.

    fig_bar_3.show()

In [235]:
#Stacked bar chart (requires 3 columns of data)
fig_bar_3 = px.bar(EU_new_data, x="Region", y= "MF (t/pp)",
                   color = "Country",
                   title = "Cumulative Material Footprint (tonnes/per person) by Region in 2023",
)

fig_bar_3.show()

# as before you can add all the fancy things

## Data Cleaning Rules to Keep in Mind

If you are comfortable with data cleaning and data science you don't have to follow these rules, but if you are new, these will make your life easier.

When in doubt look at how I have formated the different sheets in the Dataviz excel I provided as an example for both notebooks.

1. Make sure you have no data on the sheet except for the table

2. The first row should always be the table headers

3. Make sure each column has a header

4. If you make changes in your excel. Save and close the excel. If in colab delete and uplaod the new saved file. Then rerun the code block where you import the dataframe from excel.

5. Make sure there are no words or symbols in columns where you want values.

6. It is okay to leave a cell blank if there is no data, most the time (not always, but for all the graphs here) plotly will omit rows with blanks from figures, thus, only insert a zero in an empty cell if the value is truly zero.

# How to make a Map Figure

Notice in the new table we just imported you have the ISO standardized names for locations? This will allow you to make a country map of the material footprint for our ten countries.

So just like before we name our object:

    object = [CODE]

As we are making a map:

    fig_map = [CODE]

We will use the following code:

    fig_map = px.choropleth(EU_new_data,
                        locations="ISO",
                        color="MF (t/pp)",
                        hover_name="Country",)
    fig_map.show()

So we have named our figure, fig_map.

We call the plotly.express package by typing "px." then "choropleth" is the name for a map figure in Plotly.

EU_new_data is the DataFrame and the locations are found using the "ISO" column in out dataframe (table).

Then we color the countries by their material footprint using color="MF (t/pp)".

Finally when we place our mouse over a country we want it to tell us the name of the country not just the ISO abbreviation and MF (T/PP), so we write hover_name="Country" to call the name from the "Country" column.

Then we show the figure with:

    fig_map.show()

In [236]:
fig_map = px.choropleth(EU_new_data,
                    locations = "ISO",
                    color = "MF (t/pp)",
                    hover_name = "Country",)
fig_map.show()

In [237]:
#If I want to manually assign the clor scale I can do so by slightly altering the code
#Just like last time you can add and change details like title, label, hover data, template, etc.

fig_map = px.choropleth(EU_new_data, locations = "ISO",
                    title = "Material Footprint (tonnes/per person) by Country in 2023",
                    color = "MF (t/pp)",
                    hover_name = "Country",
                    color_continuous_scale = [
                      [0.0, "yellow"],
                          [0.5, "red"],
                           [1, "purple"]])
fig_map.show()

# Did you know when you hover over the map you can zoom in and out and move the map with your mouse?!
# If you Zoom in and use the Camera button in the output to take a screenshot
# This would let you fx. only focus on Europe in your data;

# Using a Notebook as an Appendix and Citation Guidelines

## Notebooks as Appendix

If you generate figures using code in your group work or MS Thesis its super helpful to include your notebook and the excel you use so an examiner or teacher can reproduce your figures. Ideally you also need README and TOML files but even providing a pre-run notebook like this and your data is sufficient. As I have done throughout, explaining each block of code and a brief interpretation is a good way of helping ensure even people less familiar with coding can follow along with what you have done. It's also a good idea to start citing your AI models, databases/datasets and literature in these notebooks.

## Generative AI Statement:

### AI level 3 use:

Use of Generative AI. Microsoft Copilot (GPT-5-based assistant; Microsoft, 2026) was used as a coding support tool to assist with Python and Plotly programming tasks. All substantive analytical decisions, interpretation of results, and final outputs were completed and verified by the author. In line with Leiden University's AI-use framework (Level 3: AI revision, human evaluation), all AI-generated outputs were critically reviewed, tested, and validated by the author. The author remains fully responsible for the submitted work

### AI level 4 use:

Use of Generative AI. Microsoft Copilot (GPT-5-based assistant; Microsoft, 2026) was used to assist with the generation and debugging of Python and Plotly code for data processing and visualization. In line with Leiden University's AI-use framework (Level 4: AI task completion, human evaluation), all AI-generated outputs were critically reviewed, tested, and validated by the author. The author remains fully responsible for all code, analyses, visualizations, interpretations, and conclusions presented in this assignment.
# Citations:

### Gen AI Model
Microsoft. (2026). Microsoft Copilot (GPT-5-based AI assistant) [Large language model].

### Python Packages:
Plotly Technologies Inc. (2024). Plotly Python graphing library.
https://plotly.com/python/

The pandas development team. (2026). Pandas-dev/pandas: Pandas [Software]. Zenodo. https://doi.org/10.5281/ZENODO.3509134

Harris, C. R., et al. (2020). Array programming with NumPy. Nature, 585(7825), 357-362.https://doi.org/10.1038/s41586-020-2649-2

### Database Sources:
Eurostat. (2024). Material footprint [Dataset]. Eurostat. https://doi.org/10.2908/CEI_PC020

United Nations. Human development index [Dataset]. United Nations. Geraadpleegd 29 september 2026, van https://hdr.undp.org/data-center/human-development-index

Lo, K., Basnet, N., Miller, E., Van Berkum, J. L., Srikanthalingam, B., Foley, B., Long, A., Toneva, P.D., Ermina, M., Klinkenberg, C. 2026. National Ecological Footprint and Biocapacity Accounts, 2026 Edition (1961-2025)[Dataset]. Results and metadata version 1.0. Produced for Footprint Data Foundation by researchers at York University and University of Iceland. https://www.fodafo.org/data

### Literature:

Cite as normal